version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
      - API_FOOTBALL_KEY=${API_FOOTBALL_KEY:-}
      - WEBHOOK_URL=${WEBHOOK_URL:-}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET:-webhook_secret}
      - API_KEY=${API_KEY:-}
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql+asyncpg://football_bot:${DB_PASSWORD:-password}@postgres:5432/football_lineup
      - ENVIRONMENT=development
      - CORS_ORIGINS=["http://localhost:3000","http://localhost:5173"]
    volumes:
      - ./backend:/app/backend:ro
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  frontend-dev:
    image: node:20-alpine
    working_dir: /app
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - app-network
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=football_bot
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_DB=football_lineup
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U football_bot -d football_lineup"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
